519

diff --git a/local/binary/extract_key b/local/binary/extract_key
--- a/local/binary/extract_key
+++ b/local/binary/extract_key
@@ -1,67 +1,99 @@
 #!/system/bin/sh
 
-
+#clear
 if [ "$aik_mob" == "1" ]; then
     out_extract_key=$local_dir/AIK-mobile/split_img
+elif [ "$aik_mob" == "2" ]; then
+    out_extract_key="$dir_avb"/"$r_name"
+    aik_mob="1"
 else
     out_extract_key=$local_dir/UnpackerSystem/extract_keys
     busybox mkdir "$out_extract_key" 2>/dev/null
+
 fi
 
 if busybox test -s "$file"; then
-    check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
-    if [ "$check_alg" != "NONE" -a ! -z "$check_alg" ]; then
-        echo
-        echo ".....Algorithm: $check_alg"
-        r="$(busybox basename $file)"
-        f_name=${r%.*}
-        offset_avb="$(python39 $binary_dir/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"
-        if [ "$offset_avb" != "None" ]; then
-            size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
-            size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
-            xxx="$(busybox expr "$offset_avb" \+ 64)"
-            offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
-            xxx="$(busybox expr "$offset_avb" \+ 72)"
-            size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
-            real_offset_key="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
-            of_hex="$(printf "%x\n" "$real_offset_key")"
-            xxd -ps -s 0x"$of_hex" -l "$size_key" "$file" | xxd -r -ps >"$out_extract_key"/"$f_name"_pubkey.pem
-            if [ $(echo $?) -eq 0 -a -s "$out_extract_key"/"$f_name"_pubkey.pem ]; then
-                if [ "$aik_mob" != "1" ]; then
-                    echo
+    if busybox test ! -z "$(avbtool info_image --image "$file" 2>/dev/null | busybox grep -o "Image size")"; then
+        check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
+
+        if [ "$check_alg" != "NONE" -a ! -z "$check_alg" ]; then
+            echo
+            echo ".....Algorithm: $check_alg"
+
+            #f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
+
+            r="$(busybox basename $file)"
+            f_name=${r%.*}
+
+            #offset_avb="$(avbtool info_image --image "$file" | busybox awk '/VBMeta offset:/ { print $3 }')"
+            #if [ ! -z "$offset_avb" ]; then
+            #offset_avb="$offset_avb"
+            #else
+            offset_avb="$(python39 $binary_dir/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"
+            #fi
+            if [ "$offset_avb" != "None" ]; then
+
+                size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
+
+                size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
+
+                xxx="$(busybox expr "$offset_avb" \+ 64)"
+                offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
+
+                xxx="$(busybox expr "$offset_avb" \+ 72)"
+
+                size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
+
+                real_offset_key="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
+
+                #busybox dd if="$file" ibs=1 skip="$real_offset_key" of="$out_extract_key"/"$f_name"_pubkey.pem bs=1 count="$size_key" &>/dev/null
+
+                of_hex="$(printf "%x\n" "$real_offset_key")"
+
+                xxd -ps -s 0x"$of_hex" -l "$size_key" "$file" | xxd -r -ps >"$out_extract_key"/"$f_name"_pubkey.pem
+
+                if [ $(echo $?) -eq 0 -a -s "$out_extract_key"/"$f_name"_pubkey.pem ]; then
+                    if [ "$aik_mob" != "1" ]; then
+                        echo
                     echo ".....$key_successfully_extracted!"
                     echo ".....$saved: "$out_extract_key"/"$f_name"_pubkey.pem"
-                    sha_sum="$(busybox sha1sum "$out_extract_key"/"$f_name"_pubkey.pem | busybox awk '{ print $1 }')"
-                    echo ".....sha1:  $sha_sum"
-                    echo
+                        sha_sum="$(busybox sha1sum "$out_extract_key"/"$f_name"_pubkey.pem | busybox awk '{ print $1 }')"
+                        echo ".....sha1:  $sha_sum"
+                        echo
+                    else
+                        #echo
+                        sha_sum="$(busybox sha1sum "$out_extract_key"/"$f_name"_pubkey.pem | busybox awk '{ print $1 }')"
+                        echo ".....sha1 public key:  $sha_sum"
+                        echo
+                    fi
                 else
-                    sha_sum="$(busybox sha1sum "$out_extract_key"/"$f_name"_pubkey.pem | busybox awk '{ print $1 }')"
-                    echo ".....sha1 public key:  $sha_sum"
+                echo ".....$key_extraction_error!"
                     echo
                 fi
             else
-                echo ".....$key_extraction_error!"
                 echo
-
+            echo ".....$error_not_found offset AVB0"
+                echo
             fi
         else
-            echo
-            echo ".....$error_not_found offset AVB0"
-            echo
+            if busybox test "$aik_mob" != "1"; then
+                echo
+            echo ".....$f_i_l_e /$nd/$file $not_signed!"
+                echo
+                #else
+                #if busybox test ! -z "$(avbtool info_image --image "$file" 2> /dev/null | busybox grep -o "Image size")"; then
+                #r="$(busybox realpath "$file")"
+                #echo
+                #echo ".....Файл $r не подписан!"
+                #echo
+            #fi
+            fi
         fi
     else
-        if busybox test "$aik_mob" != "1"; then
-            echo
-            echo ".....$file /$nd/$file $not_signed!"
-            echo
-        else
-            if busybox test ! -z "$(avbtool info_image --image "$file" 2>/dev/null | busybox grep -o "Image size")"; then
-                r="$(busybox realpath "$file")"
-                echo
-                echo ".....$file $r $not_signed!"
-                echo
-            fi
-        fi
+        r="$(busybox realpath "$file")"
+        echo
+        echo ".....$f_i_l_e $r $has_no_structure AVB"
+        echo
     fi
 else
     echo
diff --git a/local/binary/my_unmounting b/local/binary/my_unmounting
--- a/local/binary/my_unmounting
+++ b/local/binary/my_unmounting
@@ -1,37 +1,44 @@
 #!/system/bin/sh
 
+#loop=$(busybox mount | grep "$file" | cut -d" " -f1)
+
 loop=$(busybox mount | cut -d" " -f1,3 | grep "$file$" | cut -d" " -f1)
 loop_d=$(busybox mount | cut -d" " -f3 | grep "$file$")
 echo
 echo ".....$unmounting $file..."
 echo
 if [ ! -z "$loop_d" ]; then
-    pid_term="$(cat /proc/$$/status | busybox awk '/^PPid:/ { print $2 }')"
+
+
+ pid_term="$(cat /proc/$$/status | busybox awk '/^PPid:/ { print $2 }')"
     fuser -vm "$loop_d" &>$binary_dir/fuser.txt
+ 
     check_pid="$(busybox cat $binary_dir/fuser.txt | busybox grep -o "$pid_term")"
-    if [ -z "$check_pid" ]; then
-        fuser -skm "$loop_d"
-        busybox umount "$loop_d"
-        if [ "$?" -eq 0 ]; then
-            losetup -d "$loop" 2>/dev/null
-            busybox rm -rf "$loop_d"
+ if [ -z "$check_pid" ]; then
+
+ fuser -skm "$loop_d"
+ busybox umount "$loop_d"
+if [ "$?" -eq 0 ]; then
+losetup -d "$loop" 2> /dev/null
+busybox rm -rf "$loop_d"
             echo ".....$successfully_unmounted: $loop_d"
-            echo
-        else
-            echo
-            echo ".....$unmount_error!"
-        fi
-    else
-        echo
-        echo ".....$unmount_error!"
-        echo
-        echo ".....$shut_down_uka"
-        echo
-    fi
+echo
 else
-    echo
+echo
+            echo ".....$unmount_error!"
+fi
+else
+echo
+        echo ".....$unmount_error!"
+echo
+#echo ".....Сначала выйдите в терминале из папки: $loop_d"
+        echo ".....$shut_down_uka"
+echo
+fi
+else
+echo
     echo ".....$folder_not_mounted!"
-    echo
+echo
 fi
 
 busybox rm -f $binary_dir/fuser.txt
diff --git a/local/binary/rem_key b/local/binary/rem_key
--- a/local/binary/rem_key
+++ b/local/binary/rem_key
@@ -1,280 +1,300 @@
 #!/system/bin/sh
 
+#clear
 key_r() {
-    file="$1"
-    file_key="$2"
+  file="$1"
+  file_key="$2"
 
     out_extract_key=$local_dir/UnpackerSystem
 
-    if busybox test -s "$file"; then
-        check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
+  if busybox test -s "$file"; then
 
-        if busybox test "$check_alg" != "NONE" -a ! -z "$check_alg"; then
-
-            echo
+    echo
             echo ".....$replacing_key..."
-            echo
+    echo
 
-            r="$(busybox basename $file)"
+    #f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
+    r="$(busybox basename $file)"
 
-            f_name=${r%.*}
+    f_name=${r%.*}
 
             offset_avb="$(python39 $binary_dir/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"
 
-            if busybox test "$offset_avb" != "None"; then
+    if busybox test "$offset_avb" != "None"; then
 
-                size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
+      size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
 
-                size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
+      size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
 
-                xxx="$(busybox expr "$offset_avb" \+ 64)"
-                offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
+      xxx="$(busybox expr "$offset_avb" \+ 64)"
+      offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
 
-                xxx="$(busybox expr "$offset_avb" \+ 72)"
+      xxx="$(busybox expr "$offset_avb" \+ 72)"
 
-                size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
-                size_new_key="$(busybox stat -c %s "$file_key")"
-                real_offset_key="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
+      size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
+      size_new_key="$(busybox stat -c %s "$file_key")"
+      real_offset_key_dec="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
 
-                real_size_key="$(busybox expr "$real_offset_key" \+ "$size_key")"
+      real_offset_key="$(printf "%x\n" "$real_offset_key_dec")"
 
-                if busybox test "$size_key" == "$size_new_key"; then
+      real_size_key="$(busybox expr "$real_offset_key_dec" \+ "$size_key")"
 
-                    busybox dd if="$file" of="$out_extract_key"/boot_1.tmp bs="$real_offset_key" count=1 &>/dev/null
+      if busybox test "$size_key" == "$size_new_key"; then
 
-                    busybox dd if="$file" of="$out_extract_key"/boot_2.tmp bs="$real_size_key" skip=1 &>/dev/null
+        sha11="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
 
-                    busybox cat "$out_extract_key"/boot_1.tmp "$file_key" "$out_extract_key"/boot_2.tmp >/"$nds"/"$f_name"_key.img
+        bin_writekey "$file" "$real_offset_key" "$file_key"
 
-                    check_new_alg="$(avbtool info_image --image /"$nds"/"$f_name"_key.img 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
+        if [ $(echo $?) -eq 0 ]; then
+          check_new_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
 
-                    sha11="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
+          sha12="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
 
-                    sha12="$(avbtool info_image --image /"$nds"/"$f_name"_key.img | busybox awk '/^Public key \(sha1\):/ { print $4}')"
-
-                    if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
-
-                        echo ".....$successfully_created /"$nds"/"$f_name"_key.img $with_public_key: $file_key"
-                        echo
-                        echo ".....Algorithm: $check_new_alg"
-
-                        echo ".....sha1 public key: $sha12"
-                        echo
-                    else
+          if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
+            echo ".....$in_faile "$file" $key_changed_successfully_on $file_key"
+            echo
+            echo ".....Algorithm: $check_new_alg"
+            echo ".....Old sha1 public key: $sha11"
+            echo ".....New sha1 public key: $sha12"
+            echo
+          else
                         echo ".....$error_change_key!"
-                        echo
-                    fi
-                else
-                    echo
-                    echo ".....$error_key_sizes_dont_match!"
-                    echo
-                fi
-            else
-                echo
-                echo ".....$error_not_found offset AVB0"
-                echo
-            fi
+            echo
+          fi
         else
-            echo
-            echo ".....$file $file $not_signed!"
-            echo
+                   echo ".....$error_change_key!"
+          echo
         fi
+      else
+        echo
+        echo ".....$error_key_sizes_do_not_match"
+        echo
+      fi
     else
-        echo
-        echo ".....$no_file_to_process!"
-        echo
+      echo
+            echo ".....$error_not_found offset AVB0"
+      echo
     fi
-    busybox rm -f "$out_extract_key"/boot_1.tmp "$out_extract_key"/boot_2.tmp "$out_extract_key"/avb.img
-    return
+  else
+    echo
+        echo ".....$no_file_to_process!"
+    echo
+  fi
+  busybox rm -f "$out_extract_key"/avb.img
+  return
 }
 
 search_key() {
+  #clear
     echo
-    echo ".....Algorithm: $(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
-    echo
+    echo ".....Algorithm: $check_alg"
+  echo
     echo ".....$go_folder_where_public_key_located: cd /sdcard"
-    read b && $b
-    if [ $(echo $?) -eq 0 ]; then
-        clear
-        nd=$(echo $b | busybox awk '{ print $2 }' | busybox sed 's!^/!!')
-        echo
+  read b && $b
+  if [ $(echo $?) -eq 0 ]; then
+    clear
+    nd=$(echo $b | busybox awk '{ print $2 }' | busybox sed 's!^/!!')
+    echo
         echo ".....$finding_keys..."
 
-        v=$(for a in $(busybox find -maxdepth 1 -name "*.pem" -size -8k -type f); do
-            echo "$a"
-        done)
+    v=$(for a in $(busybox find -maxdepth 1 -size -8k -type f); do
 
-        set -- $v
+      if [ ! -z "$(busybox hexdump -C -n 4 "$a" | busybox grep -wo "00 00 08 00")" -a "$check_alg" == "SHA256_RSA2048" ]; then
+        echo "$a"
+      elif [ ! -z "$(busybox hexdump -C -n 4 "$a" | busybox grep -wo "00 00 10 00")" -a "$check_alg" == "SHA256_RSA4096" ]; then
+        echo "$a"
+      elif [ ! -z "$(busybox hexdump -C -n 4 "$a" | busybox grep -wo "00 00 20 00")" -a "$check_alg" == "SHA256_RSA8192" ]; then
 
-        if [ ! -z "$v" ]; then
-            clear
-            check_alg="$(busybox cat "$avb_dir"/avb.img 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
-            if [ "$check_alg" != "NONE" -a ! -z "$check_alg" ]; then
-                echo
+        echo "$a"
+
+      fi
+    done)
+
+    set -- $v
+
+    if [ ! -z "$v" ]; then
+      clear
+      echo
                 echo ".....Algorithm: $check_alg"
-            fi
-            echo
+      echo
             echo ".....$select_key:"
-            echo
+      echo
             select menu in $v "$exit_main_menu"; do
-                case $REPLY in
-                [1-9]*)
-                    i="$#"
-                    j="$#"
-                    let i=i+1
-                    let j=j+2
-                    file=$(echo "$@" | busybox cut -d' ' -f"$REPLY")
-                    if [ ! -z "$file" -a "$REPLY" -lt "$i" ]; then
-                        clear
-                        name_key="$(echo "$file" | busybox sed 's!^\./!!')"
-                        file_key=/"$nd"/"$name_key"
+        case $REPLY in
+        [1-9]*)
+          i="$#"
+          j="$#"
+          let i=i+1
+          let j=j+2
+          file=$(echo "$@" | busybox cut -d' ' -f"$REPLY")
+          if [ ! -z "$file" -a "$REPLY" -lt "$i" ]; then
+            clear
+            name_key="$(echo "$file" | busybox sed 's!^\./!!')"
+            file_key=/"$nd"/"$name_key"
 
-                        key_r "$file_real" "$file_key"
-                        return
-                        break
-                    elif [ "$REPLY" == "$i" ]; then
-                        clear
-                        return
-                        break
-                    else
-                        clear
-                        echo
-                        echo "      $anykey."
-                        search_key
-                        return
-                        break
-                    fi
-                    break
-                    ;;
-                *)
-                    clear
-                    echo
-                    echo "      $anykey"
-                    search_key
-                    return
-                    break
-                    ;;
-                esac
-            done
-        else
+            key_r "$file_real" "$file_key"
+            return
+            break
+          elif [ "$REPLY" == "$i" ]; then
+            clear
+            #main_menu
+            return
+            break
+          else
             clear
             echo
-            echo ....."$in_folder1 \"/$nd\" $no_matching_keys_to_sign."
-            echo
+                        echo "      $anykey."
+            search_key
             return
-        fi
-        echo
+            break
+          fi
+          break
+          ;;
+        *)
+          clear
+          echo
+                    echo "      $anykey"
+          search_key
+          return
+          break
+          ;;
+        esac
+      done
     else
-        echo
-        echo ".....$error_enter_dir!"
-        echo
-        echo ".....$enter_directory_correctly!"
-        echo
-        search_key
-        return
+      clear
+      echo
+            echo ....."$in_folder1 \"/$nd\" $no_matching_keys_to_sign."
+      echo
+      return
     fi
+    echo
+  else
+    echo
+        echo ".....$error_enter_dir!"
+    echo
+        echo ".....$enter_directory_correctly!"
+    echo
+    search_key
     return
+  fi
+  return
 }
 
 sel_img() {
-    echo
+  #clear
+  echo
     echo "         $public_key_replacement     "
 
-    echo
+  echo
     echo "..$go_folder_where_files_located \".img\" $for_replacement, $for_example: cd /sdcard"
-    read b && $b
-    if [ $(echo $?) -eq 0 ]; then
-        clear
-        nds=$(echo $b | busybox awk '{ print $2 }' | busybox sed 's!^/!!')
-        echo
+  read b && $b
+  if [ $(echo $?) -eq 0 ]; then
+    clear
+    nds=$(echo $b | busybox awk '{ print $2 }' | busybox sed 's!^/!!')
+    echo
         echo ".....$file_search..."
 
-        v=$(for a in $(busybox find . -maxdepth 1 -name '*.img' -type f | busybox sed 's!./!!'); do
-            if [ ! -z "$(busybox hexdump -C -n 4500 "$a" 2>/dev/null | busybox grep -Eo '41 4e 44 52 4f 49 44 21|41 56 42 30 ')" ]; then
-                echo "$a"
-            fi
-        done)
+    v=$(for a in $(busybox find . -maxdepth 1 -name '*.img' -type f | busybox sed 's!./!!'); do
+      #if [ ! -z "$(busybox hexdump -C -n 4500 "$a" 2> /dev/null | busybox grep -Eo '41 4e 44 52 4f 49 44 21|41 56 42 30 ')" ]; then
+      echo "$a"
+      #fi
+    done)
 
-        set -- $v
+    set -- $v
 
-        if [ ! -z "$v" ]; then
-            clear
-            echo
+    if [ ! -z "$v" ]; then
+      clear
+      echo
             echo ".....$select_file:"
-            echo
+      echo
             select menu in $v "$exit_main_menu" "$close_program"; do
-                case $REPLY in
-                [1-9]*)
-                    i="$#"
-                    j="$#"
-                    let i=i+1
-                    let j=j+2
-                    file=$(echo "$@" | busybox cut -d' ' -f"$REPLY")
-                    if [ ! -z "$file" -a "$REPLY" -lt "$i" ]; then
-                        clear
-                        file=/"$nds"/"$file"
-                        file_real="$file"
-                        avb_dir=$local_dir/UnpackerSystem
-                        if busybox test "$(avbtool info_image --image "$file" 2>/dev/null)"; then
-
-                            avbtool info_image --image "$file" >"$avb_dir"/avb.img
-
-                        fi
-                        search_key
-                        busybox rm -f $local_dir/UnpackerSystem/avb.img
-                        main_menu
-                        return
-                        break
-                    elif [ "$REPLY" == "$i" ]; then
-                        clear
-                        main_menu
-                        return
-                        break
-                    elif [ "$REPLY" == "$j" ]; then
-                        clear
-                        return
-                        break
-                    else
-                        clear
-                        echo
-                        echo "      $anykey."
-                        sel_img
-                        return
-                        break
-                    fi
-                    break
-                    ;;
-                *)
-                    clear
-                    echo
-                    echo "      $anykey."
-                    sel_img
-                    return
-                    break
-                    ;;
-                esac
-            done
-        else
+        case $REPLY in
+        [1-9]*)
+          i="$#"
+          j="$#"
+          let i=i+1
+          let j=j+2
+          file=$(echo "$@" | busybox cut -d' ' -f"$REPLY")
+          if [ ! -z "$file" -a "$REPLY" -lt "$i" ]; then
             clear
-            echo
-            echo ....."$in_folder1 \"/$nd\" $no_files \".img\" $for_signature."
-            echo
+            file=/"$nds"/"$file"
+            file_real="$file"
+                        avb_dir=$local_dir/UnpackerSystem
+            if busybox test "$(avbtool info_image --image "$file" 2>/dev/null)"; then
+
+              avbtool info_image --image "$file" >"$avb_dir"/avb.img
+
+              unset check_alg
+
+              check_alg="$(busybox cat "$avb_dir"/avb.img 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
+              if busybox test "$check_alg" != "NONE" -a ! -z "$check_alg"; then
+
+                #fi
+                search_key
+              else
+                echo
+                echo ".....$f_i_l_e: $file $not_signed!"
+                echo
+              fi
+            else
+              echo
+              echo ".....$f_i_l_e: $file $has_no_structure AVB!"
+              echo
+            fi
+                        busybox rm -f $local_dir/UnpackerSystem/avb.img
             main_menu
             return
-        fi
-        echo
+            break
+          elif [ "$REPLY" == "$i" ]; then
+            clear
+            main_menu
+            return
+            break
+          elif [ "$REPLY" == "$j" ]; then
+            clear
+            return
+            break
+          else
+            clear
+            echo
+                        echo "      $anykey."
+            sel_img
+            return
+            break
+          fi
+          break
+          ;;
+        *)
+          clear
+          echo
+                    echo "      $anykey."
+          sel_img
+          return
+          break
+          ;;
+        esac
+      done
     else
-        echo
-        echo ".....$error_enter_dir"
-        echo
-        echo ".....$enter_directory_correctly!"
-        echo
-        sel_img
-        return
+      clear
+      echo
+            echo ....."$in_folder1 \"/$nd\" $no_files \".img\" $for_signature."
+      echo
+      main_menu
+      return
     fi
+    echo
+  else
+    echo
+        echo ".....$error_enter_dir"
+    echo
+        echo ".....$enter_directory_correctly!"
+    echo
+    sel_img
     return
+  fi
+  return
 }
 sel_img
 
-busybox rm -f "$out_extract_key"/boot_1.tmp "$out_extract_key"/boot_2.tmp "$out_extract_key"/avb.img
+busybox rm -f "$out_extract_key"/avb.img
 unset xxx
diff --git a/local/binary/remove_key b/local/binary/remove_key
--- a/local/binary/remove_key
+++ b/local/binary/remove_key
@@ -1,80 +1,83 @@
 #!/system/bin/sh
 
+#clear
 file="$1"
 file_key="$2"
 
 if busybox test -s "$file"; then
-    check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
+  unset check_alg
+  check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
 
-    if busybox test "$check_alg" != "NONE" -a ! -z "$check_alg"; then
+  if busybox test "$check_alg" != "NONE" -a ! -z "$check_alg"; then
 
-        r="$(busybox basename $file)"
+    #f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
+    r="$(busybox basename $file)"
 
-        f_name=${r%.*}
+    f_name=${r%.*}
 
         offset_avb="$(python39 $binary_dir/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"
 
-        if busybox test "$offset_avb" != "None"; then
+    if busybox test "$offset_avb" != "None"; then
 
-            size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
+      size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
 
-            size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
+      size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
 
-            xxx="$(busybox expr "$offset_avb" \+ 64)"
-            offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
+      xxx="$(busybox expr "$offset_avb" \+ 64)"
+      offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
 
-            xxx="$(busybox expr "$offset_avb" \+ 72)"
+      xxx="$(busybox expr "$offset_avb" \+ 72)"
 
-            size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
-            size_new_key="$(busybox stat -c %s "$file_key")"
-            real_offset_key="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
+      size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
+      size_new_key="$(busybox stat -c %s "$file_key")"
+      real_offset_key_dec="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
 
-            real_size_key="$(busybox expr "$real_offset_key" \+ "$size_key")"
+      real_offset_key="$(printf "%x\n" "$real_offset_key_dec")"
 
-            if busybox test "$size_key" == "$size_new_key"; then
+      real_size_key="$(busybox expr "$real_offset_key_dec" \+ "$size_key")"
 
-                busybox dd if="$file" of=boot_1.tmp bs="$real_offset_key" count=1 &>/dev/null
+      if busybox test "$size_key" == "$size_new_key"; then
 
-                busybox dd if="$file" of=boot_2.tmp bs="$real_size_key" skip=1 &>/dev/null
+        sha11="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
 
-                busybox cat boot_1.tmp "$file_key" boot_2.tmp >"$f_name"_key.img
+        bin_writekey "$file" "$real_offset_key" "$file_key"
 
-                check_new_alg="$(avbtool info_image --image "$f_name"_key.img 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
+        if [ $(echo $?) -eq 0 ]; then
+          check_new_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
 
-                sha11="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
+          sha12="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
 
-                sha12="$(avbtool info_image --image "$f_name"_key.img | busybox awk '/^Public key \(sha1\):/ { print $4}')"
-
-                if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
-                    busybox mv -f "$f_name"_key.img "$f_name".img
-                    echo
-
-                    echo ".....Algorithm: $check_new_alg"
-                    echo ".....sha1 public key: $sha12"
-                    echo
-                else
+          if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
+            echo
+            echo ".....Algorithm: $check_new_alg"
+            echo ".....sha1 public key: $sha12"
+            echo
+          else
                     echo ".....$error_change_key!"
-                    echo
-                fi
-            else
-                echo
-                echo ".....$error_key_sizes_dont_match!"
-                echo
-            fi
+            echo
+          fi
         else
-            echo
-            echo ".....$error_not_found offset AVB0"
-            echo
+		 echo ".....$error_change_key!"
+          echo
         fi
+      else
+        echo
+        echo ".....$error_key_sizes_do_not_match"
+        echo
+      fi
     else
-        echo
-        echo ".....$file $nd/$file $not_signed!"
-        echo
+      echo
+            echo ".....$error_not_found offset AVB0"
+      echo
     fi
+  else
+    echo
+        echo ".....$f_i_l_e $nd/$file $not_signed!"
+    echo
+  fi
 else
-    echo
+  echo
     echo ".....$no_file_to_process!"
-    echo
+  echo
 fi
-busybox rm -f boot_1.tmp boot_2.tmp
 unset xxx
