translate pack_super_img

diff --git a/local/binary/pack_img_raw b/local/binary/pack_img_raw
--- a/local/binary/pack_img_raw
+++ b/local/binary/pack_img_raw
@@ -1,33 +1,129 @@
-#!/system/bin/sh
-
+#!/system/bin/shcalting_image
+#############################
+local_dir="/data/local"
+eval "$(cat "$local_dir/Unpacker_lang/$(cat "$local_dir/Unpacker_lang/selection.txt").lang")"
+#############################
 size_output_raw() {
     if busybox test -s "$outdir"/"$pack_d".new.img; then
         echo
-        echo ".....Успешно создан "$pack_d".new.img!"
+        echo ".....$successfully_created "$pack_d".new.img!"
         echo
         size_out="$(busybox stat -c %s "$outdir"/"$pack_d".new.img)"
         size_free="$(busybox expr "$(tune2fs -l "$outdir"/"$pack_d".new.img | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024)"
         echo "$size_out" >"$config"/"$pack_d"_size_out.txt
-        echo ".....Размер raw == $size_out байт"
-        echo ".....Свободное место: $size_free мб"
+        echo ".....$size1 raw == $size_out $byte"
+        echo ".....$free_space: $size_free mb"
         echo
     fi
     return
 }
 
+my_pack() {
+    echo
+    echo ".....$build_with_other file_contexts..."
+    cp ./"$config"/"$pack_d"*_fs_config ./fs_config
+    if [ -f ./file_contexts -a -f ./fs_config ]; then
+        echo
+        echo ".....$creating_image "$pack_d".new.img..."
+        echo
+        if [ "$size" = "111" ]; then
+
+            if [ -f ./"$config"/"$pack_d"*_avb.img ]; then
+
+                size_avb="$(avbtool add_hashtree_footer --partition_size "$r_size" --do_not_generate_fec --calc_max_image_size)"
+
+                chmod 755 ./"$config"/"$pack_d"_pack_avb.sh && . ./"$config"/"$pack_d"*_pack_avb.sh
+                if [ $(echo $?) -eq 0 ]; then
+                    echo
+                    echo ".....$structure_creation AVB..."
+
+                    echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$r_size" --partition_name "$part_name" --do_not_generate_fec "$prop_avb"" >./"$config"/"$pack_d"_pack_avb_str.sh
+
+                    chmod 755 ./"$config"/"$pack_d"_pack_avb_str.sh && . ./"$config"/"$pack_d"*_pack_avb_str.sh
+
+                    if [ $(echo $?) -eq 0 ]; then
+                        size_output_raw
+                    else
+                        echo
+                        echo ".....$error_creating_structure AVB!"
+                        echo
+                    fi
+                else
+                    echo
+                    echo ".....$build_error!"
+                    echo
+                fi
+
+            else
+                chmod 755 ./"$config"/"$pack_d"_gsize.sh && . ./"$config"/"$pack_d"_gsize.sh
+                if [ $(echo $?) -eq 0 ]; then
+                    size_output_raw
+                else
+                    echo
+                    echo ".....$build_error!"
+                    echo
+                fi
+            fi
+        else
+            if [ -f ./"$config"/"$pack_d"*_avb.img ]; then
+
+                size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"
+
+                chmod 755 ./"$config"/"$pack_d"*_pack_avb.sh && . ./"$config"/"$pack_d"*_pack_avb.sh
+                if [ $(echo $?) -eq 0 ]; then
+                    echo
+                    echo ".....$structure_creation AVB..."
+
+                    echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$size_obraz" --partition_name "$part_name" --do_not_generate_fec "$prop_avb"" >./"$config"/"$pack_d"_pack_avb_str.sh
+
+                    chmod 755 ./"$config"/"$pack_d"_pack_avb_str.sh && . ./"$config"/"$pack_d"*_pack_avb_str.sh
+                    if [ $(echo $?) -eq 0 ]; then
+                        size_output_raw
+                    else
+                        echo
+                        echo ".....$error_creating_structure AVB!"
+                        echo
+                    fi
+                else
+                    if [ $(echo $?) -eq 0 ]; then
+                        size_output_raw
+                    else
+                        echo
+                        echo ".....$build_error!"
+                        echo
+                    fi
+                fi
+            else
+                chmod 755 ./"$config"/"$pack_d"*_pack.sh && . ./"$config"/"$pack_d"*_pack.sh
+                if [ $(echo $?) -eq 0 ]; then
+                    size_output_raw
+                else
+                    echo
+                    echo ".....$build_error!"
+                    echo
+                fi
+            fi
+        fi
+    else
+        echo
+        echo ".....$missing_config_files_in_folder: $local_dir/UnpackerSystem/config."
+        echo
+    fi
+}
+
 if [ "$erof" == "1" ]; then
-    baze_dir=/data/local/UnpackerSystem/erofs
-    dir_avb=/data/local/UnpackerSystem/erofs/config/"$pack_d"
+    baze_dir=$local_dir/UnpackerSystem/erofs
+    dir_avb=$local_dir/UnpackerSystem/erofs/config/"$pack_d"
     config="config/$pack_d"
-    img_name=$(cat /data/local/UnpackerSystem/erofs/"$config"/"$pack_d"*_name.txt)
+    img_name=$(cat $local_dir/UnpackerSystem/erofs/"$config"/"$pack_d"*_name.txt)
 elif [ "$erof" == "0" ]; then
-    baze_dir=/data/local/UnpackerSystem
-    dir_avb=/data/local/UnpackerSystem/config/"$pack_d"
+    baze_dir=$local_dir/UnpackerSystem
+    dir_avb=$local_dir/UnpackerSystem/config/"$pack_d"
     config="config/$pack_d"
-    img_name=$(cat /data/local/UnpackerSystem/"$config"/"$pack_d"*_name.txt)
+    img_name=$(cat $local_dir/UnpackerSystem/"$config"/"$pack_d"*_name.txt)
 fi
 
-. /data/local/binary/perm_fs
+. $local_dir/binary/perm_fs
 
 size_obraz="$(cat "$dir_avb"/"$pack_d"_size.txt)"
 if busybox test -s "$dir_avb"/"$pack_d"_avb.img; then
@@ -40,127 +136,18 @@ if [ -f "$dir_avb"/"$pack_d"*_size_avb.txt ]; then
     ofsize="$(busybox expr "$offset" / 4096)"
 fi
 
-#cd /data/local/UnpackerSystem
 sed -i '/^$/d' "$config"/"$pack_d"_fs_config 2>/dev/null
-
-my_pack() {
-    echo
-    echo ".....Собираем со сторонним file_contexts..."
-    cp ./"$config"/"$pack_d"*_fs_config ./fs_config
-    if [ -f ./file_contexts -a -f ./fs_config ]; then
-        echo
-        echo ".....Создание образа "$pack_d".new.img..."
-        echo
-        if [ "$size" = "111" ]; then
-
-            if [ -f ./"$config"/"$pack_d"*_avb.img ]; then
-
-                size_avb="$(avbtool add_hashtree_footer --partition_size "$r_size" --do_not_generate_fec --calc_max_image_size)"
-
-                chmod 755 ./"$config"/"$pack_d"_pack_avb.sh && . ./"$config"/"$pack_d"*_pack_avb.sh
-                if [ $(echo $?) -eq 0 ]; then
-                    echo
-                    echo ".....Создание структуры AVB..."
-
-                    echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$r_size" --partition_name "$part_name" --do_not_generate_fec "$prop_avb"" >./"$config"/"$pack_d"_pack_avb_str.sh
-
-                    chmod 755 ./"$config"/"$pack_d"_pack_avb_str.sh && . ./"$config"/"$pack_d"*_pack_avb_str.sh
-
-                    if [ $(echo $?) -eq 0 ]; then
-                        #echo
-                        #echo ".....Успешно создан "$pack_d".new.img!"
-                        size_output_raw
-                    #echo
-                    else
-                        echo
-                        echo ".....error: Ошибка при создании структуры AVB!"
-                        echo
-                    fi
-                else
-                    echo
-                    echo ".....error: Ошибка при сборке!"
-                    echo
-                fi
-
-            else
-                chmod 755 ./"$config"/"$pack_d"_gsize.sh && . ./"$config"/"$pack_d"_gsize.sh
-                if [ $(echo $?) -eq 0 ]; then
-                    #echo
-                    #echo ".....Успешно создан "$pack_d".new.img!"
-                    size_output_raw
-                #echo
-                else
-                    echo
-                    echo ".....error: Ошибка при сборке!"
-                    echo
-                fi
-            fi
-        else
-            if [ -f ./"$config"/"$pack_d"*_avb.img ]; then
-
-                size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"
-
-                chmod 755 ./"$config"/"$pack_d"*_pack_avb.sh && . ./"$config"/"$pack_d"*_pack_avb.sh
-                if [ $(echo $?) -eq 0 ]; then
-                    echo
-                    echo ".....Создание структуры AVB..."
-
-                    echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$size_obraz" --partition_name "$part_name" --do_not_generate_fec "$prop_avb"" >./"$config"/"$pack_d"_pack_avb_str.sh
-
-                    chmod 755 ./"$config"/"$pack_d"_pack_avb_str.sh && . ./"$config"/"$pack_d"*_pack_avb_str.sh
-                    if [ $(echo $?) -eq 0 ]; then
-                        #echo
-                        #echo ".....Успешно создан "$pack_d".new.img!"
-                        size_output_raw
-                    #echo
-                    else
-                        echo
-                        echo ".....error: Ошибка при создании структуры AVB!"
-                        echo
-                    fi
-                else
-                    if [ $(echo $?) -eq 0 ]; then
-                        #echo
-                        #echo ".....Успешно создан "$pack_d".new.img!"
-                        size_output_raw
-                    #echo
-                    else
-                        echo
-                        echo ".....error: Ошибка при сборке!"
-                        echo
-                    fi
-                fi
-            else
-                chmod 755 ./"$config"/"$pack_d"*_pack.sh && . ./"$config"/"$pack_d"*_pack.sh
-                if [ $(echo $?) -eq 0 ]; then
-                    #echo
-                    #echo ".....Успешно создан "$pack_d".new.img!"
-                    size_output_raw
-                #echo
-                else
-                    echo
-                    echo ".....error: Ошибка при сборке!"
-                    echo
-                fi
-            fi
-        fi
-    else
-        echo
-        echo ".....Не хватает файлов конфигурации в папке: /data/local/UnpackerSystem/config."
-        echo
-    fi
-}
 
 if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack.sh ]; then
 
     if [ ! -f ./file_contexts ]; then
         echo
-        echo ".....Не найден сторонний file_contexts,собираем с полученным при распаковке образа..."
+        echo ".....$not_found_other file_contexts, $assemble_with_image_obtained_when_unpacking..."
         cp ./"$config"/"$pack_d"*_fs_config ./fs_config
         cp ./"$config"/"$pack_d"*_file_contexts ./file_contexts
         if [ -f ./file_contexts -a -f ./fs_config ]; then
             echo
-            echo ".....Создание образа "$pack_d".new.img..."
+            echo ".....$creating_image "$pack_d".new.img..."
             echo
             if [ "$size" = "111" ]; then
 
@@ -171,38 +158,32 @@ if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack.sh ]; then
                     chmod 755 ./"$config"/"$pack_d"_pack_avb.sh && . ./"$config"/"$pack_d"*_pack_avb.sh
                     if [ $(echo $?) -eq 0 ]; then
                         echo
-                        echo ".....Создание структуры AVB..."
+                        echo ".....$structure_creation AVB..."
 
                         echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$r_size" --partition_name "$part_name" --do_not_generate_fec "$prop_avb"" >./"$config"/"$pack_d"_pack_avb_str.sh
 
                         chmod 755 ./"$config"/"$pack_d"_pack_avb_str.sh && . ./"$config"/"$pack_d"*_pack_avb_str.sh
 
                         if [ $(echo $?) -eq 0 ]; then
-                            #echo
-                            #echo ".....Успешно создан "$pack_d".new.img!"
                             size_output_raw
-                        #echo
                         else
                             echo
-                            echo ".....error: Ошибка при создании структуры AVB!"
+                            echo ".....$error_creating_structure AVB!"
                             echo
                         fi
                     else
                         echo
-                        echo ".....error: Ошибка при сборке!"
+                        echo ".....$build_error!"
                         echo
                     fi
 
                 else
                     chmod 755 ./"$config"/"$pack_d"_gsize.sh && . ./"$config"/"$pack_d"_gsize.sh
                     if [ $(echo $?) -eq 0 ]; then
-                        #echo
-                        #echo ".....Успешно создан "$pack_d".new.img!"
                         size_output_raw
-                    #echo
                     else
                         echo
-                        echo ".....error: Ошибка при сборке!"
+                        echo ".....$build_error!"
                         echo
                     fi
                 fi
@@ -214,50 +195,41 @@ if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack.sh ]; then
                     chmod 755 ./"$config"/"$pack_d"*_pack_avb.sh && . ./"$config"/"$pack_d"*_pack_avb.sh
                     if [ $(echo $?) -eq 0 ]; then
                         echo
-                        echo ".....Создание структуры AVB..."
+                        echo ".....$structure_creation AVB..."
 
                         echo "avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$size_obraz" --partition_name "$part_name" --do_not_generate_fec "$prop_avb"" >./"$config"/"$pack_d"_pack_avb_str.sh
 
                         chmod 755 ./"$config"/"$pack_d"_pack_avb_str.sh && . ./"$config"/"$pack_d"*_pack_avb_str.sh
                         if [ $(echo $?) -eq 0 ]; then
-                            #echo
-                            #echo ".....Успешно создан "$pack_d".new.img!"
                             size_output_raw
-                        #echo
                         else
                             echo
-                            echo ".....error: Ошибка при создании структуры AVB!"
+                            echo ".....$error_creating_structure AVB!"
                             echo
                         fi
                     else
                         if [ $(echo $?) -eq 0 ]; then
-                            #echo
-                            #echo ".....Успешно создан "$pack_d".new.img!"
                             size_output_raw
-                        #echo
                         else
                             echo
-                            echo ".....error: Ошибка при сборке!"
+                            echo ".....$build_error!"
                             echo
                         fi
                     fi
                 else
                     chmod 755 ./"$config"/"$pack_d"*_pack.sh && . ./"$config"/"$pack_d"*_pack.sh
                     if [ $(echo $?) -eq 0 ]; then
-                        #echo
-                        #echo ".....Успешно создан "$pack_d".new.img!"
                         size_output_raw
-                    #echo
                     else
                         echo
-                        echo ".....error: Ошибка при сборке!"
+                        echo ".....$build_error!"
                         echo
                     fi
                 fi
             fi
         else
             echo
-            echo ".....Не хватает файлов конфигурации в папке: /data/local/UnpackerSystem/config."
+            echo ".....$missing_config_files_in_folder: $local_dir/UnpackerSystem/config."
             echo
         fi
     else
@@ -265,7 +237,7 @@ if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack.sh ]; then
     fi
 else
     echo
-    echo ".....Нет папки \""$pack_d"\" для сборки образа, или файла *_pack.sh."
+    echo ".....$no_folder \""$pack_d"\" $for_building_image_or_file_missing *_pack.sh."
     echo
 fi
 unset erof
