same fix

diff --git a/local/binary/unpack_img b/local/binary/unpack_img
--- a/local/binary/unpack_img
+++ b/local/binary/unpack_img
@@ -144,10 +144,13 @@ super() {
     simg2img "$file" "$super_dir"/super.raw.img
     echo ".....$extracting_images_from super.raw.img..."
     echo
+
     lpunpack "$super_dir"/super.raw.img "$super_dir"
+
     if [ $(echo $?) -eq 0 ]; then
       mkdir "$super_dir"/config 2>/dev/null
       lpdump --slot=0 "$super_dir"/super.raw.img >"$super_dir"/config/super_config.txt
+      lpdump --slot=1 "$file" >"$super_dir"/config/super_config1.txt
 
       super_space
 
@@ -164,7 +167,6 @@ super() {
     echo ".....$image_defined_as super.img(raw)"
     echo
     echo ".....$extracting_images_from "$file"..."
-    echo
 
     for clean_file in $(busybox find $local_dir/UnpackerSuper/* -maxdepth 1 ! -name "super*" -a ! -name "output" 2>/dev/null); do
       opla_file=$(busybox hexdump -C -n 20000 "$clean_file" 2>/dev/null | busybox grep -o "30 50 4c 41")
@@ -173,11 +175,27 @@ super() {
       fi
     done
 
-    lpunpack "$file" "$super_dir"
+    if busybox test "$real_slot" == "1"; then
+      echo ".....$removing_from_slot 1"
+      echo
+      lpunpack --slot=1 "$file" "$super_dir" && sss="0"
+    else
+      echo ".....$removing_from_slot 0"
+      echo
+      lpunpack "$file" "$super_dir" && sss="0"
+    fi
 
-    if [ $(echo $?) -eq 0 ]; then
+    if [ $(echo $sss) -eq 0 ]; then
       mkdir "$super_dir"/config 2>/dev/null
-      lpdump --slot=0 "$file" >"$super_dir"/config/super_config.txt
+      if busybox test "$real_slot" == "1"; then
+        lpdump --slot=1 "$file" >"$super_dir"/config/super_config.txt
+        lpdump --slot=0 "$file" 2>/dev/null >"$super_dir"/config/super_config1.txt
+        unset real_slot
+      else
+        lpdump --slot=0 "$file" >"$super_dir"/config/super_config.txt
+        lpdump --slot=1 "$file" 2>/dev/null >"$super_dir"/config/super_config1.txt
+        unset real_slot
+      fi
 
       super_space
 
@@ -189,6 +207,7 @@ super() {
       echo
       echo ".....$error_when_extracting_images!"
       echo
+      unset real_slot
     fi
     return
   fi
@@ -231,140 +250,6 @@ gg() {
   busybox find "$r_name" -type f | busybox sed 's!$!_f!' >>"$config"/"$r_name"_f.txt
   busybox find "$r_name" -type l | busybox sed 's!$!_l!' >>"$config"/"$r_name"_f.txt
   busybox find "$r_name" -type l | busybox xargs busybox tar -cf "$config"/"$r_name"_sim.tar
-
-}
-
-check_obraz() {
-  mkdir -p "$config" 2>/dev/null
-  if [ -z "$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")" ]; then
-    echo
-    echo ".....$image_verification..."
-    e2fsck -pf -E bmap2extent "$file" &>"$config"/"$r_name"_e2fsk.log
-  fi
-  return
-}
-
-check_sar() {
-  if [ -f "$vv/system/build.prop" ]; then
-    sar=true
-    return 0
-  else
-    sar=false
-    return 1
-  fi
-}
-
-contet() {
-  >"$config"/"$r_name".txt
-  busybox find ./"$r_name" -maxdepth 1 -type d | sed 's!\.!!' | while read a; do
-    a="$(echo "$a" | busybox sed 's!\.!\\\\\.!g')"
-    busybox grep "$a " "$config"/"$r_name"_file_contexts | busybox awk '{ print $2 }' >>"$config"/"$r_name".txt
-  done
-  rrrr_name="$(echo "$r_name" | busybox sed 's!\.!\\\\\.!g')"
-  con_nosar="$(cat "$config"/"$r_name".txt | sort | busybox uniq -c | busybox sort -nk1 | busybox tail -1 | busybox awk '{print $2}')"
-  real_name="/${rrrr_name}(/.*)? "
-
-  if [ ! -z "$(echo "$rrrr_name" | busybox grep "^persist")" ]; then
-    real_con="/${rrrr_name}(/.*)? u:object_r:persist_data_file:s0"
-  else
-    real_con="/${rrrr_name}(/.*)? ${con_nosar}"
-  fi
-  if [ -z "$(busybox grep "^$real_name" "$config"/"$r_name"_file_contexts)" ]; then
-    i=1
-    busybox sed -i -e "$i s!^!${real_con}\n!" "$config"/"$r_name"_file_contexts
-    if [ $(echo $?) -eq 0 ]; then
-      echo ".....$recording_in \"${r_name}_file_contexts\"..."
-    fi
-  fi
-  busybox rm -f "$config"/"$r_name".txt
-  return
-}
-
-con_sar() {
-  con_name="$(echo "${r_name}" | busybox sed 's!\.!\\\\\.!g')"
-  con1="/${con_name}/"
-  con2="/${con_name}(/.*)? "
-  con3="/${con_name}/system(/.*)? "
-
-  if [ -z "$(busybox grep "^${con1} " "$config"/"${r_name}"_file_contexts)" ]; then
-    con1="/${con_name}/ u:object_r:rootfs:s0"
-    i=1
-    busybox sed -i -e "$i s!^!${con1}\n!" "$config"/${r_name}_file_contexts
-  fi
-  if [ -z "$(busybox grep "^${con2}" "$config"/"${r_name}"_file_contexts)" ]; then
-    con2="/${con_name}(/.*)? u:object_r:rootfs:s0"
-    i=2
-    busybox sed -i -e "$i s!^!${con2}\n!" "$config"/${r_name}_file_contexts
-  fi
-  if [ -z "$(busybox grep "^${con3}" "$config"/"${r_name}"_file_contexts)" ]; then
-    con3="/${con_name}/system(/.*)? u:object_r:system_file:s0"
-    i=3
-    busybox sed -i -e "$i s!^!${con3}\n!" "$config"/${r_name}_file_contexts
-  fi
-  return 0
-}
-
-str_avb() {
-  base_dir=$local_dir/UnpackerSystem
-  img_name=$(cat $local_dir/UnpackerSystem/"$config"/"$r_name"_name.txt)
-
-  busybox awk '!($0 in a) {a[$0];print}' "$base_dir"/"$config"/"$r_name"_file_contexts >"$base_dir"/"$config"/"$r_name"_file_contexts.tmp && busybox mv -f "$base_dir"/"$config"/"$r_name"_file_contexts.tmp "$base_dir"/"$config"/"$r_name"_file_contexts
-
-  if [ "$sar" == "true" ]; then
-    if [ -f "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts ]; then
-      busybox cp "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts "$base_dir"/"$config"/${r_name}_file_contexts_orig && sed -i "s!^/!/${r_name}/!" "$base_dir"/"$config"/${r_name}_file_contexts_orig
-    fi
-
-    con_sar #функция для SAR
-
-    echo ".....Detected image \"System as Root\""
-
-  elif
-    [ "$sar" == "false" ]
-  then
-
-    echo ".....Detected image not \"System as Root\""
-    contet #функция для не SAR
-  fi
-
-  dir_avb=$local_dir/UnpackerSystem/config
-
-  q="$(busybox basename $file)"
-  file_exten_raw="$(echo "$img_name" | busybox grep -o "raw$")"
-  file_exten_avb=${q##*.}
-  if [ "$file_exten_avb" == "PARTITION" -a -z "$file_exten_raw" ]; then
-    file_avb="/$nd"/"$img_name".PARTITION
-  else
-    file_avb="/$nd"/"$img_name".img
-  fi
-  full_avb="$(avbtool info_image --image "$file_avb" 2>"$dir_avb"/"$r_name"/"$r_name"_avb.log)"
-
-  if [ ! -z "$(echo "$full_avb" | grep -Eo "Image Size:|VBMeta offset:")" ]; then
-
-    echo "$full_avb" | busybox awk '/Partition Name:/ { print $3 }' >"$dir_avb"/"$r_name"/"$r_name"_part_name.txt
-    echo "$full_avb" >"$dir_avb"/"$r_name"/"$r_name"_avb.img
-    echo
-    echo ".....$find_struct AVB!"
-
-    if busybox test -s "$dir_avb"/"$r_name"/"$r_name"_avb.img; then
-
-      echo 'make_ext4fs -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb.sh
-
-      echo 'make_ext4fs -s -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb_sparse.sh
-
-    else
-      echo
-      echo ".....$error_creating_configuration_file!"
-      echo
-    fi
-  elif [ ! -z "$(cat "$dir_avb"/"$r_name"/"$r_name"_avb.log | busybox grep -Eo "Given image does")" ]; then
-    echo >/dev/null
-  else
-    echo
-    echo ".....$discovery_error AVB!"
-    echo
-  fi
-  return
 }
 
 if [ ! -z "$opla" ]; then
@@ -413,6 +298,15 @@ else
   rm -rf "$config"
   if [ -f "$file" ]; then
 
+    check_obraz() {
+      mkdir -p "$config" 2>/dev/null
+      if [ -z "$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")" ]; then
+        echo
+        echo ".....$image_verification..."
+        e2fsck -pf -E bmap2extent "$file" &>"$config"/"$r_name"_e2fsk.log
+      fi
+      return
+    }
     check_obraz
 
     echo ".....$unpacking ${file}..."
@@ -440,6 +334,15 @@ else
       h=$(busybox find "$r_name" | busybox grep [[:space:]])
       vv="$r_name"
 
+      check_sar() {
+        if [ -f "$vv/system/build.prop" ]; then
+          sar=true
+          return 0
+        else
+          sar=false
+          return 1
+        fi
+      }
       check_sar
 
       >"$config"/"$r_name"_gg_d.txt
@@ -455,6 +358,120 @@ else
       done >>"$config"/"$r_name"_tmp_f.txt
       cat "$config"/"$r_name"_tmp_f.txt | busybox awk '!($0 in a) {a[$0];print}' >"$config"/"$r_name"_gg_f.txt && rm -f "$config"/"$r_name"_tmp_f.txt
 
+      contet() {
+        >"$config"/"$r_name".txt
+        busybox find ./"$r_name" -maxdepth 1 -type d | sed 's!\.!!' | while read a; do
+          a="$(echo "$a" | busybox sed 's!\.!\\\\\.!g')"
+          busybox grep "$a " "$config"/"$r_name"_file_contexts | busybox awk '{ print $2 }' >>"$config"/"$r_name".txt
+        done
+        rrrr_name="$(echo "$r_name" | busybox sed 's!\.!\\\\\.!g')"
+        con_nosar="$(cat "$config"/"$r_name".txt | sort | busybox uniq -c | busybox sort -nk1 | busybox tail -1 | busybox awk '{print $2}')"
+        real_name="/${rrrr_name}(/.*)? "
+
+        if [ ! -z "$(echo "$rrrr_name" | busybox grep "^persist")" ]; then
+          real_con="/${rrrr_name}(/.*)? u:object_r:persist_data_file:s0"
+        else
+          real_con="/${rrrr_name}(/.*)? ${con_nosar}"
+        fi
+        if [ -z "$(busybox grep "^$real_name" "$config"/"$r_name"_file_contexts)" ]; then
+          i=1
+          busybox sed -i -e "$i s!^!${real_con}\n!" "$config"/"$r_name"_file_contexts
+          if [ $(echo $?) -eq 0 ]; then
+            echo ".....$recording_in \"${r_name}_file_contexts\"..."
+          fi
+        fi
+        busybox rm -f "$config"/"$r_name".txt
+        return
+      }
+
+      con_sar() {
+        con_name="$(echo "${r_name}" | busybox sed 's!\.!\\\\\.!g')"
+        con1="/${con_name}/"
+        con2="/${con_name}(/.*)? "
+        con3="/${con_name}/system(/.*)? "
+
+        if [ -z "$(busybox grep "^${con1} " "$config"/"${r_name}"_file_contexts)" ]; then
+          con1="/${con_name}/ u:object_r:rootfs:s0"
+          i=1
+          busybox sed -i -e "$i s!^!${con1}\n!" "$config"/${r_name}_file_contexts
+        fi
+        if [ -z "$(busybox grep "^${con2}" "$config"/"${r_name}"_file_contexts)" ]; then
+          con2="/${con_name}(/.*)? u:object_r:rootfs:s0"
+          i=2
+          busybox sed -i -e "$i s!^!${con2}\n!" "$config"/${r_name}_file_contexts
+        fi
+        if [ -z "$(busybox grep "^${con3}" "$config"/"${r_name}"_file_contexts)" ]; then
+          con3="/${con_name}/system(/.*)? u:object_r:system_file:s0"
+          i=3
+          busybox sed -i -e "$i s!^!${con3}\n!" "$config"/${r_name}_file_contexts
+        fi
+        return 0
+      }
+
+      str_avb() {
+        base_dir=$local_dir/UnpackerSystem
+        img_name=$(cat $local_dir/UnpackerSystem/"$config"/"$r_name"_name.txt)
+
+        busybox awk '!($0 in a) {a[$0];print}' "$base_dir"/"$config"/"$r_name"_file_contexts >"$base_dir"/"$config"/"$r_name"_file_contexts.tmp && busybox mv -f "$base_dir"/"$config"/"$r_name"_file_contexts.tmp "$base_dir"/"$config"/"$r_name"_file_contexts
+
+        if [ "$sar" == "true" ]; then
+          if [ -f "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts ]; then
+            busybox cp "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts "$base_dir"/"$config"/${r_name}_file_contexts_orig && sed -i "s!^/!/${r_name}/!" "$base_dir"/"$config"/${r_name}_file_contexts_orig
+          fi
+
+          con_sar
+
+          echo ".....Detected image \"System as Root\""
+
+        elif
+          [ "$sar" == "false" ]
+        then
+
+          echo ".....Detected image not \"System as Root\""
+          contet
+        fi
+
+        dir_avb=$local_dir/UnpackerSystem/config
+
+        q="$(busybox basename $file)"
+        file_exten_raw="$(echo "$img_name" | busybox grep -o "raw$")"
+        file_exten_avb=${q##*.}
+        if [ "$file_exten_avb" == "PARTITION" -a -z "$file_exten_raw" ]; then
+          file_avb="/$nd"/"$img_name".PARTITION
+        else
+          file_avb="/$nd"/"$img_name".img
+        fi
+
+        full_avb="$(avbtool info_image --image "$file_avb" 2>"$dir_avb"/"$r_name"/"$r_name"_avb.log)"
+
+        if [ ! -z "$(echo "$full_avb" | grep -Eo "Image Size:|VBMeta offset:")" ]; then
+
+          echo "$full_avb" | busybox awk '/Partition Name:/ { print $3 }' >"$dir_avb"/"$r_name"/"$r_name"_part_name.txt
+          echo "$full_avb" >"$dir_avb"/"$r_name"/"$r_name"_avb.img
+          echo
+          echo ".....$find_struct AVB!"
+
+          if busybox test -s "$dir_avb"/"$r_name"/"$r_name"_avb.img; then
+
+            echo 'make_ext4fs -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb.sh
+
+            echo 'make_ext4fs -s -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb_sparse.sh
+
+          else
+            echo
+            echo ".....$error_creating_configuration_file!"
+            echo
+          fi
+        elif [ ! -z "$(cat "$dir_avb"/"$r_name"/"$r_name"_avb.log | busybox grep -Eo "Given image does")" ]; then
+          echo >/dev/null
+        else
+          echo
+          echo ".....$discovery_error AVB!"
+          echo
+
+        fi
+        return
+      }
       str_avb
 
       if busybox test -s "$config"/"$r_name"*_space.txt]; then
@@ -486,6 +503,7 @@ else
         echo "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
       fi
+
     else
       echo
       echo "\033[31;47;1m   .....$unpacking_error!              \033[0m"
