hh

diff --git a/local/binary/unpack_img b/local/binary/unpack_img
--- a/local/binary/unpack_img
+++ b/local/binary/unpack_img
@@ -1,62 +1,57 @@
 #!/system/bin/sh
-
+#############################
+local_dir="/data/local"
+eval "$(cat "$local_dir/Unpacker_lang/$(cat "$local_dir/Unpacker_lang/selection.txt").lang")"
+#############################
 nd=$nd
 
-cd /data/local/UnpackerSystem
-#r_name=$(echo $file | grep -Eo "system|vendor")
-
-#r_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F"-|[+]|[.]|[{]|[(]" '{ print $1 }')
+cd $local_dir/UnpackerSystem
 
 r="$(busybox basename $file)"
 r_name=${r%.*}
 config="config/$r_name"
 parts="$(echo "$r" | busybox grep -o "PARTITION")"
 exten=${r##*.}
-#echo "$parts"
-#echo "$r"
-#echo "$exten"
 
-super_dir=/data/local/UnpackerSuper
+super_dir=$local_dir/UnpackerSuper
 opla=$(busybox hexdump -C -n 20000 "$file" | busybox grep -o "30 50 4c 41")
 erofs="$(busybox hexdump -C -n 2000 "$file" | busybox grep -o 'e2 e1 f5 e0')"
 sparse_super=$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")
 
 erfs() {
-
   if [ -d erofs/"$r_name" ]; then
 
     echo
-    echo ".....Удаление старой папки /data/local/UnpackerSystem/erofs/"$r_name""
+    echo ".....$deleting_old_folder $local_dir/UnpackerSystem/erofs/"$r_name""
     umount erofs/"$r_name" 2>/dev/null
     busybox rm -rf erofs/"$r_name" 2>/dev/null
   fi
-
   mkdir -p erofs/"$r_name" 2>/dev/null
   erofsfuse "$file" erofs/"$r_name" &>/dev/null
   if [ $(echo $?) -eq 0 ]; then
     echo
-    echo ".....Распаковка $file..."
+    echo ".....$unpacking $file..."
     busybox tar -cf erofs.tar erofs/"$r_name"
     if [ $(echo $?) -eq 0 ]; then
       umount erofs/"$r_name"
       if [ $(echo $?) -eq 0 ]; then
-        busybox tar -xf erofs.tar -C /data/local/UnpackerSystem
+        busybox tar -xf erofs.tar -C $local_dir/UnpackerSystem
         echo
-        echo "\033[33;1m.....Успешно распаковано! \033[0m"
+        echo "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
       else
         echo
-        echo ".....Ошибка распаковки(...not extract tar)"
+        echo ".....$unpacking_error (...not extract tar)"
         echo
       fi
     else
       echo
-      echo ".....Ошибка распаковки(...not create tar)"
+      echo ".....$unpacking_error (...not create tar)"
       echo
     fi
   else
     echo
-    echo ".....Ошибка распаковки(...not mount)"
+    echo ".....$unpacking_error (...not mount)"
     echo
   fi
   umount erofs/"$r_name" 2>/dev/null
@@ -119,27 +114,27 @@ END {print a*b}')"
   if [ "$sim" == 0 ]; then
     rr="$(busybox expr "$max_size_super2" - "$F")"
     ss=$(busybox expr "$rr" / 1024 / 1024)
-    echo ".....Сумма размеров полученных образов, меньше максимального на $rr байт(~$ss mb)"
-    echo " real = $F байт  <  max = $max_size_super2 байт"
+    echo ".....$sum_sizes_collected_images_less_than_maximum1 $rr $byte(~$ss mb)"
+    echo " real = $F $byte  <  max = $max_size_super2 $byte"
 
   elif [ "$sim" == 1 ]; then
     rr="$(busybox expr "$F" - "$max_size_super2")"
     ss=$(busybox expr "$rr" / 1024 / 1024)
-    echo ".....Сумма размеров полученных образов, больше допустимого на $rr байт(~$ss mb)!"
-    echo " real = $F байт  >  max = $max_size_super2 байт"
+    echo ".....$sum_sizes_collected_images_more_than1 $rr $byte(~$ss mb)!"
+    echo " real = $F $byte  >  max = $max_size_super2 $byte"
   fi
 
 }
 
 super() {
-  if [ ! -z "$opla" -a ! -z "$sparse_super" ]; then
+  if [ ! -z "$opla" -a ! -z "$sparse_super" ]; then$error_when_extracting_images
     echo
     echo ".....Образ определён, как super.img(sparse)"
     echo
-    echo ".....Конвертация "$file"(sparse) -> $super_dir/super.raw.img(raw)..."
+    echo ".....$converting "$file"(sparse) -> $super_dir/super.raw.img(raw)..."
     echo
 
-    for clean_file in $(busybox find /data/local/UnpackerSuper/* -maxdepth 1 ! -name "super*" -a ! -name "output" 2>/dev/null); do
+    for clean_file in $(busybox find $local_dir/UnpackerSuper/* -maxdepth 1 ! -name "super*" -a ! -name "output" 2>/dev/null); do
       opla_file=$(busybox hexdump -C -n 20000 "$clean_file" 2>/dev/null | busybox grep -o "30 50 4c 41")
       if [ -z "$opla_file" ]; then
         busybox rm -rf $clean_file
@@ -147,7 +142,7 @@ super() {
     done
 
     simg2img "$file" "$super_dir"/super.raw.img
-    echo ".....Извлечение образов из super.raw.img..."
+    echo ".....$extracting_images_from super.raw.img..."
     echo
     lpunpack "$super_dir"/super.raw.img "$super_dir"
     if [ $(echo $?) -eq 0 ]; then
@@ -161,17 +156,17 @@ super() {
       echo
     else
       echo
-      echo ".....Ошибка при извлечении образов!"
+      echo ".....$error_when_extracting_images!"
       echo
     fi
   elif [ ! -z "$opla" -a -z "$sparse_super" ]; then
     echo
     echo ".....Образ определён, как super.img(raw)"
     echo
-    echo ".....Извлечение образов из "$file"..."
+    echo ".....$extracting_images_from "$file"..."
     echo
 
-    for clean_file in $(busybox find /data/local/UnpackerSuper/* -maxdepth 1 ! -name "super*" -a ! -name "output" 2>/dev/null); do
+    for clean_file in $(busybox find $local_dir/UnpackerSuper/* -maxdepth 1 ! -name "super*" -a ! -name "output" 2>/dev/null); do
       opla_file=$(busybox hexdump -C -n 20000 "$clean_file" 2>/dev/null | busybox grep -o "30 50 4c 41")
       if [ -z "$opla_file" ]; then
         busybox rm -rf $clean_file
@@ -192,7 +187,7 @@ super() {
 
     else
       echo
-      echo ".....Ошибка при извлечении образов!"
+      echo ".....$error_when_extracting_images!"
       echo
     fi
     return
@@ -201,7 +196,7 @@ super() {
 }
 
 gg() {
-  cd /data/local/UnpackerSystem
+  cd $local_dir/UnpackerSystem
   busybox find "$r_name" -type f | busybox grep [[:space:]] | while read a; do
     if [ ! -z "$(echo ${a##*/} | busybox grep [[:space:]])" ]; then
       ff="${a%\/*}"/"$(echo ${a##*/} | busybox sed 's! !_!g')"
@@ -235,9 +230,141 @@ gg() {
   busybox find "$r_name" -type d | busybox sed 's!$!_d!' >"$config"/"$r_name"_f.txt
   busybox find "$r_name" -type f | busybox sed 's!$!_f!' >>"$config"/"$r_name"_f.txt
   busybox find "$r_name" -type l | busybox sed 's!$!_l!' >>"$config"/"$r_name"_f.txt
-
   busybox find "$r_name" -type l | busybox xargs busybox tar -cf "$config"/"$r_name"_sim.tar
 
+}
+
+check_obraz() {
+  mkdir -p "$config" 2>/dev/null
+  if [ -z "$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")" ]; then
+    echo
+    echo ".....Проверка образа..."
+    e2fsck -pf -E bmap2extent "$file" &>"$config"/"$r_name"_e2fsk.log
+  fi
+  return
+}
+
+check_sar() {
+  if [ -f "$vv/system/build.prop" ]; then
+    sar=true
+    return 0
+  else
+    sar=false
+    return 1
+  fi
+}
+
+contet() {
+  >"$config"/"$r_name".txt
+  busybox find ./"$r_name" -maxdepth 1 -type d | sed 's!\.!!' | while read a; do
+    a="$(echo "$a" | busybox sed 's!\.!\\\\\.!g')"
+    busybox grep "$a " "$config"/"$r_name"_file_contexts | busybox awk '{ print $2 }' >>"$config"/"$r_name".txt
+  done
+  rrrr_name="$(echo "$r_name" | busybox sed 's!\.!\\\\\.!g')"
+  con_nosar="$(cat "$config"/"$r_name".txt | sort | busybox uniq -c | busybox sort -nk1 | busybox tail -1 | busybox awk '{print $2}')"
+  real_name="/${rrrr_name}(/.*)? "
+
+  if [ ! -z "$(echo "$rrrr_name" | busybox grep "^persist")" ]; then
+    real_con="/${rrrr_name}(/.*)? u:object_r:persist_data_file:s0"
+  else
+    real_con="/${rrrr_name}(/.*)? ${con_nosar}"
+  fi
+  if [ -z "$(busybox grep "^$real_name" "$config"/"$r_name"_file_contexts)" ]; then
+    i=1
+    busybox sed -i -e "$i s!^!${real_con}\n!" "$config"/"$r_name"_file_contexts
+    if [ $(echo $?) -eq 0 ]; then
+      echo ".....Запись в \"${r_name}_file_contexts\"..."
+    fi
+  fi
+  busybox rm -f "$config"/"$r_name".txt
+  return
+}
+
+con_sar() {
+  con_name="$(echo "${r_name}" | busybox sed 's!\.!\\\\\.!g')"
+  con1="/${con_name}/"
+  con2="/${con_name}(/.*)? "
+  con3="/${con_name}/system(/.*)? "
+
+  if [ -z "$(busybox grep "^${con1} " "$config"/"${r_name}"_file_contexts)" ]; then
+    con1="/${con_name}/ u:object_r:rootfs:s0"
+    i=1
+    busybox sed -i -e "$i s!^!${con1}\n!" "$config"/${r_name}_file_contexts
+  fi
+  if [ -z "$(busybox grep "^${con2}" "$config"/"${r_name}"_file_contexts)" ]; then
+    con2="/${con_name}(/.*)? u:object_r:rootfs:s0"
+    i=2
+    busybox sed -i -e "$i s!^!${con2}\n!" "$config"/${r_name}_file_contexts
+  fi
+  if [ -z "$(busybox grep "^${con3}" "$config"/"${r_name}"_file_contexts)" ]; then
+    con3="/${con_name}/system(/.*)? u:object_r:system_file:s0"
+    i=3
+    busybox sed -i -e "$i s!^!${con3}\n!" "$config"/${r_name}_file_contexts
+  fi
+  return 0
+}
+
+str_avb() {
+  base_dir=$local_dir/UnpackerSystem
+  img_name=$(cat $local_dir/UnpackerSystem/"$config"/"$r_name"_name.txt)
+
+  busybox awk '!($0 in a) {a[$0];print}' "$base_dir"/"$config"/"$r_name"_file_contexts >"$base_dir"/"$config"/"$r_name"_file_contexts.tmp && busybox mv -f "$base_dir"/"$config"/"$r_name"_file_contexts.tmp "$base_dir"/"$config"/"$r_name"_file_contexts
+
+  if [ "$sar" == "true" ]; then
+    if [ -f "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts ]; then
+      busybox cp "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts "$base_dir"/"$config"/${r_name}_file_contexts_orig && sed -i "s!^/!/${r_name}/!" "$base_dir"/"$config"/${r_name}_file_contexts_orig
+    fi
+
+    con_sar #функция для SAR
+
+    echo ".....Detected image \"System as Root\""
+
+  elif
+    [ "$sar" == "false" ]
+  then
+
+    echo ".....Detected image not \"System as Root\""
+    contet #функция для не SAR
+  fi
+
+  dir_avb=$local_dir/UnpackerSystem/config
+
+  q="$(busybox basename $file)"
+  file_exten_raw="$(echo "$img_name" | busybox grep -o "raw$")"
+  file_exten_avb=${q##*.}
+  if [ "$file_exten_avb" == "PARTITION" -a -z "$file_exten_raw" ]; then
+    file_avb="/$nd"/"$img_name".PARTITION
+  else
+    file_avb="/$nd"/"$img_name".img
+  fi
+  full_avb="$(avbtool info_image --image "$file_avb" 2>"$dir_avb"/"$r_name"/"$r_name"_avb.log)"
+
+  if [ ! -z "$(echo "$full_avb" | grep -Eo "Image Size:|VBMeta offset:")" ]; then
+
+    echo "$full_avb" | busybox awk '/Partition Name:/ { print $3 }' >"$dir_avb"/"$r_name"/"$r_name"_part_name.txt
+    echo "$full_avb" >"$dir_avb"/"$r_name"/"$r_name"_avb.img
+    echo
+    echo ".....Обнаружена структура AVB!"
+
+    if busybox test -s "$dir_avb"/"$r_name"/"$r_name"_avb.img; then
+
+      echo 'make_ext4fs -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb.sh
+
+      echo 'make_ext4fs -s -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb_sparse.sh
+
+    else
+      echo
+      echo ".....Ошибка при создании фвйла конфигурации!"
+      echo
+    fi
+  elif [ ! -z "$(cat "$dir_avb"/"$r_name"/"$r_name"_avb.log | busybox grep -Eo "Given image does")" ]; then
+    echo >/dev/null
+  else
+    echo
+    echo ".....Ошибка при обнаружении AVB!"
+    echo
+  fi
+  return
 }
 
 if [ ! -z "$opla" ]; then
@@ -258,7 +385,7 @@ elif [ ! -z "$erofs" -a ! -z "$sparse_super" ]; then
   echo
   echo "\033[33;1m.....$file имеет файловую систему erofs!\033[0m"
   echo
-  echo ".....Конвертация "$file" -> "$file_raw"..."
+  echo ".....$converting "$file" -> "$file_raw"..."
 
   simg2img "$file" "$file_raw" && file="$file_raw"
   if [ ! -z "$(getprop ro.product.cpu.abilist64)" ]; then
@@ -286,29 +413,11 @@ else
   rm -rf "$config"
   if [ -f "$file" ]; then
 
-    check_obraz() {
-      mkdir -p "$config" 2>/dev/null
-      #ld_path="$(echo "$LD_LIBRARY_PATH" | busybox grep -o "/data/local/binary/lib")"
-      #if [ -z "$LD_LIBRARY_PATH" ]; then
-      #export LD_LIBRARY_PATH="/data/local/binary/lib"
-      #else
-      #if [ -z "$ld_path" ]; then
-      #export LD_LIBRARY_PATH="/data/local/binary/lib:$LD_LIBRARY_PATH"
-      #fi
-      #fi
-      if [ -z "$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")" ]; then
-        echo
-        echo ".....Проверка образа..."
-        e2fsck -pf -E bmap2extent "$file" &>"$config"/"$r_name"_e2fsk.log
-      fi
-      return
-    }
     check_obraz
 
-    #echo
     echo ".....Распаковка ${file}..."
 
-    python39 /data/local/binary/bin_system/imgextractor1.py "$file" "$PWD"
+    python39 $local_dir/binary/bin_system/imgextractor1.py "$file" "$PWD"
     if [ $(echo $?) -eq 0 ]; then
       if [ -d ./"$r_name" -a -s "$config"/"$r_name"_fs_config ]; then
         busybox sed -i '/logd / s!0x4000040000040!0x440000040!' "$config"/"$r_name"_fs_config
@@ -329,23 +438,8 @@ else
       fi
 
       h=$(busybox find "$r_name" | busybox grep [[:space:]])
-
-      #if [ -d "$r_name"/"$r_name" -a "$r_name" == "system" ]; then
-      #vv="$r_name"/"$r_name"
-      #elif [ -d "$r_name" ]; then
       vv="$r_name"
-      #fi
 
-      check_sar() {
-        if [ -f "$vv/system/build.prop" ]; then
-          #echo "$sar"
-          sar=true
-          return 0
-        else
-          sar=false
-          return 1
-        fi
-      }
       check_sar
 
       >"$config"/"$r_name"_gg_d.txt
@@ -361,132 +455,7 @@ else
       done >>"$config"/"$r_name"_tmp_f.txt
       cat "$config"/"$r_name"_tmp_f.txt | busybox awk '!($0 in a) {a[$0];print}' >"$config"/"$r_name"_gg_f.txt && rm -f "$config"/"$r_name"_tmp_f.txt
 
-      #new
-      contet() {
-        >"$config"/"$r_name".txt
-        busybox find ./"$r_name" -maxdepth 1 -type d | sed 's!\.!!' | while read a; do
-          a="$(echo "$a" | busybox sed 's!\.!\\\\\.!g')"
-          busybox grep "$a " "$config"/"$r_name"_file_contexts | busybox awk '{ print $2 }' >>"$config"/"$r_name".txt
-        done
-        rrrr_name="$(echo "$r_name" | busybox sed 's!\.!\\\\\.!g')"
-        con_nosar="$(cat "$config"/"$r_name".txt | sort | busybox uniq -c | busybox sort -nk1 | busybox tail -1 | busybox awk '{print $2}')"
-        real_name="/${rrrr_name}(/.*)? "
-
-        if [ ! -z "$(echo "$rrrr_name" | busybox grep "^persist")" ]; then
-          real_con="/${rrrr_name}(/.*)? u:object_r:persist_data_file:s0"
-        else
-          real_con="/${rrrr_name}(/.*)? ${con_nosar}"
-        fi
-        if [ -z "$(busybox grep "^$real_name" "$config"/"$r_name"_file_contexts)" ]; then
-          i=1
-          busybox sed -i -e "$i s!^!${real_con}\n!" "$config"/"$r_name"_file_contexts
-          if [ $(echo $?) -eq 0 ]; then
-            echo ".....Запись в \"${r_name}_file_contexts\"..."
-          fi
-        fi
-        busybox rm -f "$config"/"$r_name".txt
-        return
-      }
-
-      con_sar() {
-        con_name="$(echo "${r_name}" | busybox sed 's!\.!\\\\\.!g')"
-        con1="/${con_name}/"
-        con2="/${con_name}(/.*)? "
-        con3="/${con_name}/system(/.*)? "
-
-        if [ -z "$(busybox grep "^${con1} " "$config"/"${r_name}"_file_contexts)" ]; then
-          con1="/${con_name}/ u:object_r:rootfs:s0"
-          i=1
-          busybox sed -i -e "$i s!^!${con1}\n!" "$config"/${r_name}_file_contexts
-        fi
-        if [ -z "$(busybox grep "^${con2}" "$config"/"${r_name}"_file_contexts)" ]; then
-          con2="/${con_name}(/.*)? u:object_r:rootfs:s0"
-          i=2
-          busybox sed -i -e "$i s!^!${con2}\n!" "$config"/${r_name}_file_contexts
-        fi
-        if [ -z "$(busybox grep "^${con3}" "$config"/"${r_name}"_file_contexts)" ]; then
-          con3="/${con_name}/system(/.*)? u:object_r:system_file:s0"
-          i=3
-          busybox sed -i -e "$i s!^!${con3}\n!" "$config"/${r_name}_file_contexts
-        fi
-        return 0
-      }
-
-      str_avb() {
-        base_dir=/data/local/UnpackerSystem
-        img_name=$(cat /data/local/UnpackerSystem/"$config"/"$r_name"_name.txt)
-
-        busybox awk '!($0 in a) {a[$0];print}' "$base_dir"/"$config"/"$r_name"_file_contexts >"$base_dir"/"$config"/"$r_name"_file_contexts.tmp && busybox mv -f "$base_dir"/"$config"/"$r_name"_file_contexts.tmp "$base_dir"/"$config"/"$r_name"_file_contexts
-
-        if [ "$sar" == "true" ]; then
-          #echo "/system/ u:object_r:rootfs:s0" >> "$base_dir"/"$config"/${r_name}_file_contexts
-          if [ -f "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts ]; then
-            busybox cp "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts "$base_dir"/"$config"/${r_name}_file_contexts_orig && sed -i "s!^/!/${r_name}/!" "$base_dir"/"$config"/${r_name}_file_contexts_orig
-          fi
-
-          con_sar #функция для SAR
-
-          echo ".....Detected image \"System as Root\""
-
-        elif
-          [ "$sar" == "false" ]
-        then
-
-          echo ".....Detected image not \"System as Root\""
-          contet #функция для не SAR
-        fi
-
-        #file_avb="/$nd"/"$img_name".img
-        dir_avb=/data/local/UnpackerSystem/config
-
-        q="$(busybox basename $file)"
-        #echo "$q"
-        file_exten_raw="$(echo "$img_name" | busybox grep -o "raw$")"
-        file_exten_avb=${q##*.}
-        if [ "$file_exten_avb" == "PARTITION" -a -z "$file_exten_raw" ]; then
-          file_avb="/$nd"/"$img_name".PARTITION
-        else
-          file_avb="/$nd"/"$img_name".img
-        fi
-        #echo "$file_avb"
-        #echo "$file_exten_avb"
-
-        #python39 /data/local/binary/bin_system/find_avb.py "$file_avb" "41564230000000" "$dir_avb"
-
-        full_avb="$(avbtool info_image --image "$file_avb" 2>"$dir_avb"/"$r_name"/"$r_name"_avb.log)"
-
-        if [ ! -z "$(echo "$full_avb" | grep -Eo "Image Size:|VBMeta offset:")" ]; then
-
-          echo "$full_avb" | busybox awk '/Partition Name:/ { print $3 }' >"$dir_avb"/"$r_name"/"$r_name"_part_name.txt
-          echo "$full_avb" >"$dir_avb"/"$r_name"/"$r_name"_avb.img
-          echo
-          echo ".....Обнаружена структура AVB!"
-
-          if busybox test -s "$dir_avb"/"$r_name"/"$r_name"_avb.img; then
-
-            echo 'make_ext4fs -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb.sh
-
-            echo 'make_ext4fs -s -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb_sparse.sh
-
-          else
-            echo
-            echo ".....Ошибка при создании фвйла конфигурации!"
-            echo
-          fi
-        elif [ ! -z "$(cat "$dir_avb"/"$r_name"/"$r_name"_avb.log | busybox grep -Eo "Given image does")" ]; then
-          echo >/dev/null
-        else
-          echo
-          echo ".....Ошибка при обнаружении AVB!"
-          echo
-
-        #return
-        fi
-        return
-      }
       str_avb
-
-      #. "$dir"/cap_unpak
 
       if busybox test -s "$config"/"$r_name"*_space.txt]; then
         echo
@@ -496,12 +465,11 @@ else
 
       if [ ! -z "$h" ]; then
         echo
-        echo "\033[33;1m.....Успешно распаковано! \033[0m"
+        echo "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
         echo "...В образе "${file}" есть файлы с пробелами, исправляем..."
         echo "$h" >"$config"/"$r_name"_space.txt
         gg
-        #. "$dir"/cap_unpak
 
         if [ $(echo $?) -eq 0 ]; then
 
@@ -515,23 +483,18 @@ else
         fi
       else
         echo
-        echo "\033[33;1m.....Успешно распаковано! \033[0m"
+        echo "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
       fi
-
-    #echo
-    #echo "\033[33;1m.....Успешно распаковано! \033[0m"
-    #echo
     else
       echo
-      echo "\033[31;47;1m   .....error: Ошибка распаковки!              \033[0m"
+      echo "\033[31;47;1m   .....error: $unpacking_error!              \033[0m"
       echo
       busybox rm -f "$config"/"$r_name"
     fi
   else
     echo
-    echo ".....Образа "$file", нет в папке: /data/local/UnpackerSystem."
+    echo ".....Образа "$file", нет в папке: $local_dir/UnpackerSystem."
     echo
   fi
 fi
- 
