517

diff --git a/local/binary/unpack_img b/local/binary/unpack_img
--- a/local/binary/unpack_img
+++ b/local/binary/unpack_img
@@ -15,6 +15,7 @@ exten=${r##*.}
 
 super_dir=$local_dir/UnpackerSuper
 opla=$(busybox hexdump -C -n 20000 "$file" | busybox grep -o "30 50 4c 41")
+zst=$(busybox hexdump -C -n 2000 "$file" | busybox grep -o "28 b5 2f fd")
 erofs="$(busybox hexdump -C -n 2000 "$file" | busybox grep -o 'e2 e1 f5 e0')"
 sparse_super=$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")
 
@@ -37,7 +38,7 @@ erfs() {
       if [ $(echo $?) -eq 0 ]; then
         busybox tar -xf erofs.tar -C $local_dir/UnpackerSystem
         echo
-        echo "\033[33;1m.....$successfully_unpacked! \033[0m"
+        echo -e "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
       else
         echo
@@ -150,12 +151,12 @@ super() {
     if [ $(echo $?) -eq 0 ]; then
       mkdir "$super_dir"/config 2>/dev/null
       lpdump --slot=0 "$super_dir"/super.raw.img >"$super_dir"/config/super_config.txt
-      lpdump --slot=1 "$file" >"$super_dir"/config/super_config1.txt
+      lpdump --slot=1 "$super_dir"/super.raw.img >"$super_dir"/config/super_config1.txt
 
       super_space
 
       echo
-      echo "\033[33;1m.....$images_successfully_extracted_to_folder: $super_dir \033[0m"
+      echo -e "\033[33;1m.....$images_successfully_extracted_to_folder: $super_dir \033[0m"
       echo
     else
       echo
@@ -200,7 +201,7 @@ super() {
       super_space
 
       echo
-      echo "\033[33;1m.....$images_successfully_extracted_to_folder: $super_dir \033[0m"
+      echo -e "\033[33;1m.....$images_successfully_extracted_to_folder: $super_dir \033[0m"
       echo
 
     else
@@ -210,6 +211,46 @@ super() {
       unset real_slot
     fi
     return
+  fi
+  return
+}
+
+zst_my() {
+  if [ ! -z "$zst" ]; then
+    echo
+    echo ".....$image_defined_as .zst"
+    echo
+    echo ".....$converting $file(zst) -> $super_dir/super.tmp.img..."
+    echo
+
+    for clean_file in $(busybox find /data/local/UnpackerSuper/* -maxdepth 1 ! -name "super*" -a ! -name "output" 2>/dev/null); do
+      opla_file=$(busybox hexdump -C -n 20000 "$clean_file" 2>/dev/null | busybox grep -o "30 50 4c 41")
+      if [ -z "$opla_file" ]; then
+        busybox rm -rf $clean_file
+      fi
+    done
+
+    busybox mv "$file" ${file}.zst && file=${file}.zst
+    if [ -z "$(getprop ro.product.cpu.abilist64)" ]; then
+      echo
+      zstd32 -df "$file" -o "$super_dir"/super.tmp.img
+    else
+      zstd64 -df "$file" -o "$super_dir"/super.tmp.img
+    fi
+
+    if [ $(echo $?) -eq 0 ]; then
+      file_orig="$(echo "$file" | busybox sed 's!.zst!!')"
+      busybox mv "$file" "$file_orig"
+
+      file="$super_dir"/super.tmp.img
+      opla=$(busybox hexdump -C -n 20000 "$file" | busybox grep -o "30 50 4c 41")
+      sparse_super=$(busybox hexdump -C -n 20000 "$file" | grep -o "3a ff 26 ed")
+    fi
+
+  else
+    echo
+    echo ".....$convert_error!"
+    echo
   fi
   return
 }
@@ -251,24 +292,26 @@ gg() {
   busybox find "$r_name" -type l | busybox sed 's!$!_l!' >>"$config"/"$r_name"_f.txt
   busybox find "$r_name" -type l | busybox xargs busybox tar -cf "$config"/"$r_name"_sim.tar
 }
-
-if [ ! -z "$opla" ]; then
+if [ ! -z "$zst" ]; then
+  zst_my
+  super
+elif [ ! -z "$opla" ]; then
   super
 elif [ ! -z "$erofs" -a -z "$sparse_super" ]; then
   if [ ! -z "$(getprop ro.product.cpu.abilist64)" ]; then
     echo
-    echo "\033[33;1m.....$file $has_file_system erofs!\033[0m"
+    echo -e "\033[33;1m.....$file $has_file_system erofs!\033[0m"
 
     . unpack_img_erofs
   else
     echo
-    echo "\033[33;1m.....$file $has_file_system erofs!\033[0m"
+    echo -e "\033[33;1m.....$file $has_file_system erofs!\033[0m"
     erfs
   fi
 elif [ ! -z "$erofs" -a ! -z "$sparse_super" ]; then
   file_raw="/$nd"/"$r_name".raw.img
   echo
-  echo "\033[33;1m.....$file $has_file_system erofs!\033[0m"
+  echo -e "\033[33;1m.....$file $has_file_system erofs!\033[0m"
   echo
   echo ".....$converting "$file" -> "$file_raw"..."
 
@@ -423,9 +466,7 @@ else
 
           echo ".....Detected image \"System as Root\""
 
-        elif
-          [ "$sar" == "false" ]
-        then
+        elif [ "$sar" == "false" ]; then
 
           echo ".....Detected image not \"System as Root\""
           contet
@@ -482,7 +523,7 @@ else
 
       if [ ! -z "$h" ]; then
         echo
-        echo "\033[33;1m.....$successfully_unpacked! \033[0m"
+        echo -e "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
         echo "...$in_image "${file}" $there_files_with_spaces_fix..."
         echo "$h" >"$config"/"$r_name"_space.txt
@@ -500,13 +541,13 @@ else
         fi
       else
         echo
-        echo "\033[33;1m.....$successfully_unpacked! \033[0m"
+        echo -e "\033[33;1m.....$successfully_unpacked! \033[0m"
         echo
       fi
 
     else
       echo
-      echo "\033[31;47;1m   .....$unpacking_error!              \033[0m"
+      echo -e "\033[31;47;1m   .....$unpacking_error!              \033[0m"
       echo
       busybox rm -f "$config"/"$r_name"
     fi
diff --git a/local/binary/unpack_img_erofs b/local/binary/unpack_img_erofs
--- a/local/binary/unpack_img_erofs
+++ b/local/binary/unpack_img_erofs
@@ -51,118 +51,6 @@ gg() {
     busybox find "$r_name" -type l | busybox sed 's!$!_l!' >>"$config"/"$r_name"_f.txt
     busybox find "$r_name" -type l | busybox xargs busybox tar -cf "$config"/"$r_name"_sim.tar
 }
-
-check_sar() {
-    if [ -f "$vv/system/build.prop" ]; then
-        sar=true
-        return 0
-    else
-        sar=false
-        return 1
-    fi
-}
-
-contet() {
-    >"$config"/"$r_name".txt
-    busybox find ./"$r_name" -maxdepth 1 -type d | sed 's!\.!!' | while read a; do
-        a="$(echo "$a" | busybox sed 's!\.!\\\\\.!g')"
-        busybox grep "$a " "$config"/"$r_name"_file_contexts | busybox awk '{ print $2 }' >>"$config"/"$r_name".txt
-    done
-    rrrr_name="$(echo "$r_name" | busybox sed 's!\.!\\\\\.!g')"
-    con_nosar="$(cat "$config"/"$r_name".txt | sort | busybox uniq -c | busybox sort -nk1 | busybox tail -1 | busybox awk '{print $2}')"
-    real_name="/${rrrr_name}(/.*)? "
-    if [ ! -z "$(echo "$rrrr_name" | busybox grep "^persist")" ]; then
-        real_con="/${rrrr_name}(/.*)? u:object_r:persist_data_file:s0"
-    else
-        real_con="/${rrrr_name}(/.*)? ${con_nosar}"
-    fi
-    if [ -z "$(busybox grep "^$real_name" "$config"/"$r_name"_file_contexts)" ]; then
-        i=1
-        busybox sed -i -e "$i s!^!${real_con}\n!" "$config"/"$r_name"_file_contexts
-        if [ $(echo $?) -eq 0 ]; then
-            echo ".....$recording_in \"${r_name}_file_contexts\"..."
-        fi
-    fi
-    busybox rm -f "$config"/"$r_name".txt
-    return
-}
-
-con_sar() {
-    con_name="$(echo "${r_name}" | busybox sed 's!\.!\\\\\.!g')"
-    con1="/${con_name}/"
-    con2="/${con_name}(/.*)? "
-    con3="/${con_name}/system(/.*)? "
-    if [ -z "$(busybox grep "^${con1} " "$config"/"${r_name}"_file_contexts)" ]; then
-        con1="/${con_name}/ u:object_r:rootfs:s0"
-        i=1
-        busybox sed -i -e "$i s!^!${con1}\n!" "$config"/${r_name}_file_contexts
-    fi
-    if [ -z "$(busybox grep "^${con2}" "$config"/"${r_name}"_file_contexts)" ]; then
-        con2="/${con_name}(/.*)? u:object_r:rootfs:s0"
-        i=2
-        busybox sed -i -e "$i s!^!${con2}\n!" "$config"/${r_name}_file_contexts
-    fi
-    if [ -z "$(busybox grep "^${con3}" "$config"/"${r_name}"_file_contexts)" ]; then
-        con3="/${con_name}/system(/.*)? u:object_r:system_file:s0"
-        i=3
-        busybox sed -i -e "$i s!^!${con3}\n!" "$config"/${r_name}_file_contexts
-    fi
-    return 0
-}
-
-str_avb() {
-    base_dir=$local_dir/UnpackerSystem/erofs
-    img_name=$(cat $local_dir/UnpackerSystem/erofs/"$config"/"$r_name"_name.txt)
-    busybox awk '!($0 in a) {a[$0];print}' "$base_dir"/"$config"/"$r_name"_file_contexts >"$base_dir"/"$config"/"$r_name"_file_contexts.tmp && busybox mv -f "$base_dir"/"$config"/"$r_name"_file_contexts.tmp "$base_dir"/"$config"/"$r_name"_file_contexts
-    if [ "$sar" == "true" ]; then
-        if [ -f "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts ]; then
-            busybox cp "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts "$base_dir"/"$config"/${r_name}_file_contexts_orig && sed -i "s!^/!/${r_name}/!" "$base_dir"/"$config"/${r_name}_file_contexts_orig
-        fi
-        con_sar
-        echo ".....Detected image \"System as Root\""
-    elif
-        [ "$sar" == "false" ]
-    then
-
-        echo ".....Detected image not \"System as Root\""
-        contet
-    fi
-    dir_avb=$local_dir/UnpackerSystem/erofs/config
-    q="$(busybox basename $file)"
-    file_exten_raw="$(echo "$img_name" | busybox grep -o "raw$")"
-    file_exten_avb=${q##*.}
-    if [ "$file_exten_avb" == "PARTITION" -a -z "$file_exten_raw" ]; then
-        file_avb="/$nd"/"$img_name".PARTITION
-    else
-        file_avb="/$nd"/"$img_name".img
-    fi
-    full_avb="$(avbtool info_image --image "$file_avb" 2>"$dir_avb"/"$r_name"/"$r_name"_avb.log)"
-    if [ ! -z "$(echo "$full_avb" | grep -Eo "Image Size:|VBMeta offset:")" ]; then
-        echo "$full_avb" | busybox awk '/Partition Name:/ { print $3 }' >"$dir_avb"/"$r_name"/"$r_name"_part_name.txt
-        echo "$full_avb" >"$dir_avb"/"$r_name"/"$r_name"_avb.img
-        echo
-        echo ".....$find_struct AVB!"
-        if busybox test -s "$dir_avb"/"$r_name"/"$r_name"_avb.img; then
-
-            echo 'make_ext4fs -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb.sh
-
-            echo 'make_ext4fs -s -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb_sparse.sh
-
-        else
-            echo
-            echo ".....$error_creating_configuration_file!"
-            echo
-        fi
-    elif [ ! -z "$(cat "$dir_avb"/"$r_name"/"$r_name"_avb.log | busybox grep -Eo "Given image does")" ]; then
-        echo >/dev/null
-    else
-        echo
-        echo ".....$discovery_error AVB!"
-        echo
-    fi
-    return
-}
-
 cd $local_dir/UnpackerSystem/erofs
 echo
 echo ".....$deleting_old_folder \""$r_name"\" $and_configuration_files..."
@@ -208,6 +96,16 @@ if [ -f "$file" ]; then
         fi
         h=$(busybox find "$r_name" | busybox grep [[:space:]])
         vv="$r_name"
+
+        check_sar() {
+            if [ -f "$vv/system/build.prop" ]; then
+                sar=true
+                return 0
+            else
+                sar=false
+                return 1
+            fi
+        }
         check_sar
         >"$config"/"$r_name"_gg_d.txt
         busybox find "$vv" -maxdepth 1 ! -path 'lost+found' -a ! -path "$vv" -type d | while read a; do
@@ -220,6 +118,107 @@ if [ -f "$file" ]; then
             busybox find "$a" ! -path 'lost+found' -type f | busybox xargs busybox stat -c '%N %u %g %a' 2>/dev/null
         done >>"$config"/"$r_name"_tmp_f.txt
         cat "$config"/"$r_name"_tmp_f.txt | busybox awk '!($0 in a) {a[$0];print}' >"$config"/"$r_name"_gg_f.txt && rm -f "$config"/"$r_name"_tmp_f.txt
+
+        contet() {
+            >"$config"/"$r_name".txt
+            busybox find ./"$r_name" -maxdepth 1 -type d | sed 's!\.!!' | while read a; do
+                a="$(echo "$a" | busybox sed 's!\.!\\\\\.!g')"
+                busybox grep "$a " "$config"/"$r_name"_file_contexts | busybox awk '{ print $2 }' >>"$config"/"$r_name".txt
+            done
+            rrrr_name="$(echo "$r_name" | busybox sed 's!\.!\\\\\.!g')"
+            con_nosar="$(cat "$config"/"$r_name".txt | sort | busybox uniq -c | busybox sort -nk1 | busybox tail -1 | busybox awk '{print $2}')"
+            real_name="/${rrrr_name}(/.*)? "
+            if [ ! -z "$(echo "$rrrr_name" | busybox grep "^persist")" ]; then
+                real_con="/${rrrr_name}(/.*)? u:object_r:persist_data_file:s0"
+            else
+                real_con="/${rrrr_name}(/.*)? ${con_nosar}"
+            fi
+            if [ -z "$(busybox grep "^$real_name" "$config"/"$r_name"_file_contexts)" ]; then
+                i=1
+                busybox sed -i -e "$i s!^!${real_con}\n!" "$config"/"$r_name"_file_contexts
+                if [ $(echo $?) -eq 0 ]; then
+                    echo ".....$recording_in \"${r_name}_file_contexts\"..."
+                fi
+            fi
+            busybox rm -f "$config"/"$r_name".txt
+            return
+        }
+
+        con_sar() {
+            con_name="$(echo "${r_name}" | busybox sed 's!\.!\\\\\.!g')"
+            con1="/${con_name}/"
+            con2="/${con_name}(/.*)? "
+            con3="/${con_name}/system(/.*)? "
+            if [ -z "$(busybox grep "^${con1} " "$config"/"${r_name}"_file_contexts)" ]; then
+                con1="/${con_name}/ u:object_r:rootfs:s0"
+                i=1
+                busybox sed -i -e "$i s!^!${con1}\n!" "$config"/${r_name}_file_contexts
+            fi
+            if [ -z "$(busybox grep "^${con2}" "$config"/"${r_name}"_file_contexts)" ]; then
+                con2="/${con_name}(/.*)? u:object_r:rootfs:s0"
+                i=2
+                busybox sed -i -e "$i s!^!${con2}\n!" "$config"/${r_name}_file_contexts
+            fi
+            if [ -z "$(busybox grep "^${con3}" "$config"/"${r_name}"_file_contexts)" ]; then
+                con3="/${con_name}/system(/.*)? u:object_r:system_file:s0"
+                i=3
+                busybox sed -i -e "$i s!^!${con3}\n!" "$config"/${r_name}_file_contexts
+            fi
+            return 0
+        }
+
+        str_avb() {
+            base_dir=$local_dir/UnpackerSystem/erofs
+            img_name=$(cat $local_dir/UnpackerSystem/erofs/"$config"/"$r_name"_name.txt)
+            busybox awk '!($0 in a) {a[$0];print}' "$base_dir"/"$config"/"$r_name"_file_contexts >"$base_dir"/"$config"/"$r_name"_file_contexts.tmp && busybox mv -f "$base_dir"/"$config"/"$r_name"_file_contexts.tmp "$base_dir"/"$config"/"$r_name"_file_contexts
+            if [ "$sar" == "true" ]; then
+                if [ -f "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts ]; then
+                    busybox cp "$base_dir"/${r_name}/system/etc/selinux/plat_file_contexts "$base_dir"/"$config"/${r_name}_file_contexts_orig && sed -i "s!^/!/${r_name}/!" "$base_dir"/"$config"/${r_name}_file_contexts_orig
+                fi
+                con_sar
+                echo ".....Detected image \"System as Root\""
+
+            elif [ "$sar" == "false" ]; then
+
+                echo ".....Detected image not \"System as Root\""
+                contet
+            fi
+            dir_avb=$local_dir/UnpackerSystem/erofs/config
+            q="$(busybox basename $file)"
+            file_exten_raw="$(echo "$img_name" | busybox grep -o "raw$")"
+            file_exten_avb=${q##*.}
+            if [ "$file_exten_avb" == "PARTITION" -a -z "$file_exten_raw" ]; then
+                file_avb="/$nd"/"$img_name".PARTITION
+            else
+                file_avb="/$nd"/"$img_name".img
+            fi
+            full_avb="$(avbtool info_image --image "$file_avb" 2>"$dir_avb"/"$r_name"/"$r_name"_avb.log)"
+            if [ ! -z "$(echo "$full_avb" | grep -Eo "Image Size:|VBMeta offset:")" ]; then
+                echo "$full_avb" | busybox awk '/Partition Name:/ { print $3 }' >"$dir_avb"/"$r_name"/"$r_name"_part_name.txt
+                echo "$full_avb" >"$dir_avb"/"$r_name"/"$r_name"_avb.img
+                echo
+                echo ".....$find_struct AVB!"
+                if busybox test -s "$dir_avb"/"$r_name"/"$r_name"_avb.img; then
+
+                    echo 'make_ext4fs -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb.sh
+
+                    echo 'make_ext4fs -s -J -T -1 -S ./file_contexts -C ./fs_config -l "$size_avb" -a /"$pack_d" "$outdir"/"$pack_d".new.img $pack_d' >"$dir_avb"/"$r_name"/"$r_name"_pack_avb_sparse.sh
+
+                else
+                    echo
+                    echo ".....$error_creating_configuration_file!"
+                    echo
+                fi
+            elif [ ! -z "$(cat "$dir_avb"/"$r_name"/"$r_name"_avb.log | busybox grep -Eo "Given image does")" ]; then
+                echo >/dev/null
+            else
+                echo
+                echo ".....$discovery_error AVB!"
+                echo
+            fi
+            return
+        }
+
         str_avb
         if busybox test -s "$config"/"$r_name"*_space.txt; then
             echo
@@ -228,7 +227,7 @@ if [ -f "$file" ]; then
         fi
         if [ ! -z "$h" ]; then
             echo
-            echo "\033[33;1m.....$successfully_unpacked! \033[0m"
+            echo -e "\033[33;1m.....$successfully_unpacked! \033[0m"
             echo
             echo "...$in_image "${file}" $there_files_with_spaces_fix..."
             echo "$h" >"$config"/"$r_name"_space.txt
@@ -244,12 +243,12 @@ if [ -f "$file" ]; then
             fi
         else
             echo
-            echo "\033[33;1m.....$successfully_unpacked! \033[0m"
+            echo -e "\033[33;1m.....$successfully_unpacked! \033[0m"
             echo
         fi
     else
         echo
-        echo "\033[31;47;1m ...$error_incorrect_extraction_of_files
+        echo -e "\033[31;47;1m ...$error_incorrect_extraction_of_files
  $folder $local_dir/UnpackerSystem/erofs/$r_name $will__not_available_for_assembly_in ext4!             \033[0m"
         echo
         busybox rm -rf "$config" config/"$r_name"_fs_config config/"$r_name"_file_contexts
